flowchart TD
    1[Arguments] -->    2[Check_arguments]
                        2 -->   8[Arguments are good]
                        2 -->   3[Non numeric]
                        2 -->   4[Duplicates]
                        2 -->   5[No arguments]
                        2 -->   6[INT_MIN or INT_MAX reached]
                                3 & 4 & 5 & 6 -->   11[Return: Error]
                                8 -->   9[START]
                                        9 -->   10[Is STACK_A sorted ?]
                                                10 -->  |YES| 10YES[PUSH_SWAP DONE125/100]
                                                10 -->  |NO| 10NO[2222]